<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	'To buy'		=> 'Acheter',  
	'To build'		=> 'Construire',
	'To move units'	=> 'Déplacer des troupes',
	'To attack'		=> 'Attaquer',
		
	/* Text */
	'Text_Not_User_Turn'		=> 'Aucune action disponible <br> Veuillez attendre votre tour...',
	'Text_Land_No_Resource'		=> 'Pas de ressource',
	'Text_Land_No_Building'		=> 'Pas de construction',
	'Text_Land_Frontier'		=> 'Frontières',
	'Text_Land_No_User_Frontier'=> "Vous n'avez pas de pays ami frontalier",
	'Text_Land_No_Other_Frontier'=> "Vous n'avez pas de pays ennemi frontalier",
	'Text_No_More_Money'		=> "Vous n'avez plus d'argent",
	'Text_Resource_In_Land'		=> 'Ressources en',
	'Text_In'					=> 'en',
	'Text_Units'				=> 'Unités',
	'Text_Units_In'				=> 'Unités en',
	'Text_Owner'				=> 'Propriétaire',
	'Text_Total'				=> 'Total',
	'Text_Income'				=> 'Revenus',
	'Text_Owner_Player'			=> 'Vous',
	'Text_Resource'				=> 'Ressource',
	'Text_Defender'				=> 'Défenseur',
	'Text_Attacker'				=> 'Attaquant',
	'Text_Victory'				=> 'Victoire',
	'Text_Units_Pending'		=> 'unités présentes',
	'Text_Buy_To_Recruit'		=> "Troupes à recruter",
	'Text_Build_In_Land'		=> 'Construit en',
	'Text_Build_Able_Land'		=> 'Constructions possibles en',
	'Text_Build_Other'			=> 'Construire un autre bâtiment',
	'Text_Move_Cant'			=> "Pas d'unité à deplacer",
	'Text_Move_Units_NB'		=> "Unités à deplacer",
	'Text_Move_Able_Land'		=> 'Destinations possibles',
	'Text_Atk_Able_Land'		=> 'Pays attaquants possibles',
	'Text_Atk_Units_NB'			=> 'Unités à mobiliser',
	'Text_Land_Nothing_To_Build'=> 'Rien à construire',
	'Text_Not_Owner'			=> "Vous n'êtes pas le propriétaire",
	'Text_Are_Owner'			=> "Vous êtes le propriétaire",
	'Text_Conquered_This_Turn' 	=> "conquis ce tour.",
	'Text_Income_By_Buildings'	=> 'bâtimens',
	'Text_Income_By_Lands'		=> 'pays',

	/* Buttons */
	'Button_Land_Build' 		=> 'Construire',
	'Button_Land_Buy' 			=> 'Recruter',
	'Button_Land_Atk' 			=> 'Attaquer',
	'Button_Land_Atk_With' 		=> 'Attaquer avec',
	'Button_Land_Move' 			=> 'Deplacer des troupes',
	'Button_Move_Click' 		=> 'Deplacer en',
	'Button_Return' 			=> 'Retour',
	'Button_Land_Move_Conquest'	=> 'Déplacement impossible',

	/* Tooltips */
	'Attack this land.'										=> 'Attaquer ce pays.',
	'Move units to another land.'							=> 'Deplacer des troupes vers un autre pays.',
	'Construct buildings on the land: fort, camp, mines.'	=> 'Construire des bâtiments dans le pays : fort, camp, mines.',
	'Buy units for this land.'								=> 'Acheter des troupes pour ce pays.',

	/* Error */
	'Error' 					=> 'Erreur inconnue.',
	'Error_Turn' 				=> "Erreur : votre tour est terminé.",
	'Error_Gold' 				=> "Erreur : vous n'avez pas assez d'argent.",
	'Error_Units' 				=> "Erreur : vous devez conserver au minimum 1 unité sur votre territoire.",
	'Error_Conquest' 			=> "Erreur : ce pays a été conquis ce tour.",
];
?>
