<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	
	/* Text */
	'Text_Not_User_Turn'		=> 'Aucune action disponible <br> Veuillez attendre votre tour...',	
	'Text_Land_No_Ressource'	=> 'Pas de ressource',
	'Text_Land_No_Building'		=> 'Pas de construction',
	'Text_Land_Frontier'		=> 'Frontières',
	'Text_Buy_Not_More_Money'	=> "Vous n'avez plus d'argent",
		
	/* Buttons */
	'Button_Land_Build' => 'Construire',
	'Button_Land_Buy' => 'Acheter',
	'Button_Land_Atk' => 'Attaquer',
	'Button_Land_Move' => 'Deplacer des troupes',
];
?>