<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */
	'Title_Lobby_{params}' => 'Partie de {params}',

    /* Text*/
    'Continent_Rules' => '* Information * : Vous avez 1 chance sur 5 de vous retrouver en Antarctique Ã  la place du continent choisit !',
	'Text_Wait_Owner' => 'Partie en attente du propriétaire...',
	'Text_Owner' => 'Propriétaire de la partie',
    'Bot_Name_{id}' => 'Ordi {id}',
    'Text_Add_Bot' => 'Ordinateur ajouté.',
    'Text_Bot_Del' => 'Ordinateur supprimé.',
    'Text_Player_Game_Ban' => 'Joueur exclu de la partie.',
    'Text_Error_Action' => 'Impossible de réaliser cette action.',

    /* Buttons */ 
    'Button_Sart_Game' => 'Lancer la partie',
    'Button_Add_Bot' => 'Ajouter un ordi',
    'Button_Ready' => 'Je suis prêt',
    'Button_Cancel' => 'Annuler',
    'Button_Not_Ready' => 'Occupé',
    'Button_Rdy' => 'Je suis prêt',
    'Button_Add_Friend' => 'Inviter un ami',
    'Button_Add_Random' => 'Inviter un joueur aléatoire',

    /* Form */
    'Form_Continent' => 'Continent de départ',
    'Form_Difficulty' => 'Difficulté',
    'Form_Color' => 'Couleur',
    'Form_Status' => 'Statut',
    'Form_Player' => 'Joueur',

	/* Tab */
	'Tab_User_Name' => 'Nom du joueur',	
	'Tab_Color_Name' => 'Couleur',		
	'Tab_Region_Player' => 'Region de départ',
		
	/* Error */
    'Text_Forced_left' => 'Vous avez été renvoyé du salon',
];
?>