<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	'Title_Create' => 'Créer votre partie',
    'Title_Loby' => 'Liste des salons de parties',
    'Title_Join' => 'Rejoindre une partie',
    'Title_Loading' => 'Chargement...',
		
	/* Tabs */
	'Tab_Game_Name' => 'Nom de la partie',
	'Tab_Owner_Name' => "Proprietaire",
	'Tab_Max_Player' => "Nombre de joueurs",
	'Tab_Create_Time' => "Date de creation",
	'Tab_Rejoin' => "Rejoindre",

    /* Text*/
    'Creation_Rules' => 'Veuillez completer le formulaire pour créer votre partie :',
    'Join_Rules' => 'Veuillez entrer le mot de passe de la partie :',
    'Chat_General' => 'Chat général',
    'Error_Name_Already_Use' => 'Nom de partie déjà utilisé',
    'Error_Password_Incorrect' => 'Un mot de passe est nécessaire : mot de passe incorrect.',
    'Error_User_Already_In_Game' => 'Vous êtes déjà dans une autre partie !',
    'Error_Game_Full' => 'La partie est pleine.',
    'Error_Game_Not_Exist' => "La partie n'existe plus.",
    'Error_Start_Multiple_Color' => "La partie n'a pas pu démarrer : Plusieurs joueurs ont la même couleur.",
    'Error_Start_Not_Ready' => "La partie n'a pas pu démarrer : les joueurs ne sont pas prêts.",
    'Error_Start_Stop' => "La partie n'a pas pu démarrer.",
    'Success_User_Left_Game' => 'Vous avez quitté la partie.',
    'Success_User_Enter_Game_{params}' => 'Vous avez rejoint la partie : {params}.',
    'Error_Max_Player_Nb' => "Le nombre de joueur maximum est 10.",
    'Text_Second_{nb}' => 'il y a {nb} sec',
    'Text_Min_{nb}' => 'Il y a {nb} min',
    'Text_Hour_{nb}' => 'Il y a {nb} h',
    'Text_Yesterday' => 'Hier',
    'Text_Week' => 'Cette semaine',
    'Text_Date' => 'd/m/Y',
    'Text_Load_Title' => 'Etapes',
    'Text_Load_Step_0' => 'Assignation des ressources',
    'Text_Load_Step_1' => 'Assignation des territoires',
    'Text_Load_Step_2' => 'Gestion des joueurs',
    'Text_Load_Step_3' => 'Gestion des tours',
    'Text_Load_Step_4' => 'Finalisation',

    /* Buttons */ 
    'Button_Send' => 'Envoyer',
    'Button_Game_Create' => 'Créer une partie',
    'Button_Game_Enter' => 'Entrer dans la partie',
    'Button_Game_Return' => 'Retourner dans la partie',
    'Button_Game_Spec' => 'Regarder la partie',
    'Button_Game_Ban' => 'Vous avez été bannis',
    'Button_Game_End' => 'Partie terminée',

    /* Form */
    'Form_Create_Name' => 'Nom de la partie',
    'Form_Create_Time' => 'Création',
    'Form_Create_Pwd' => 'Mot de passe',
    'Form_Create_Max_Player' => 'Nombre de joueurs',
    'Form_Create_Mod_Id' => 'Mode de jeu',
    'Form_Create_Difficulty_Id' => 'Difficulté',
    'Form_Create_Map_Id' => 'Carte',
    'Form_Create_Owner' => 'Hôte de la partie',
    'Form_Join_Pwd' => 'Mot de passe',
];
?>