<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */

    // header
	'Logout'       	=> 'Déconnexion',
	'Profile'       => 'Profil',
	'Friends'       => 'Amis',
	'Stats'       	=> 'Stats',
	'Language'      => 'Language',
    
		
	// In game header	
	// box title
	'Box_Title_Ranking' => 'Classement',
	'Box_Title_News' => 'News',
	'Box_Title_Pact' => 'Traités en cours',
		
	// Buttons
	'Button_Chat' => "Voir le chat",
	'Button_Diplomacy' => "Diplomatie ",
	'Button_Turn_Own' => "Fin du tour",
		
	// Text
	'Text_Gold' => 'Or',
	'Text_Income' => 'Revenu',
	'Text_Country' => 'Régions',
	'Text_Units' => 'Unités',
	'Text_Turn_Own' => 'Temps restant',
	'Text_Turn_Finished' => 'Tour terminé',
	'Text_Turn_Other' 	=> 'Patientez, tour de.',
	'Text_Your_turn'	=>  "C'est votre tour !",
	'Text_Lost_Connection'=>  'Connexion perdue avec le serveur',
		
];
?>