<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */
	'Title_Map' => 'Carte de la partie',

	/* Text */
    'Text_Menu_Top_Gold' => 'Or',
    'Text_Menu_Top_Income' => 'Revenu',
    'Text_Menu_Top_Country' => 'Régions',
    'Text_Menu_Top_Units' => 'Unités',
    'Text_Turn_Own' => 'Temps restant',
    'Text_Turn_Finished' => 'Tour terminé',
    'Text_Turn_Other_{name}' => 'Tour de {name}.',

    /* Buttons */ 
    'Button_Chat_{nb}' => "Voir le chat ({nb})",
    'Button_Diplomacy' => "Diplomatie ",
    'Button_Turn_Own' => "Fin du tour",

    /* Help */

    /* Box */ 
    // box title
    'Box_Title_Ranking' => 'Classement',
    'Box_Title_News' => 'News',
    'Box_Title_Pact' => 'Traités en cours',

    /* Modal */
    'Modal_Loading' => 'Chargement en cours',
    // Modal title
  	'Modal_Title_Land' => 'Informations',
  	'Modal_Title_Gestion' => 'Gestion',
  	'Modal_Title_Chat' => 'Chat',
  	'Modal_Title_NewTurn' => '',
  	'Modal_Title_Diplomacy' => 'Diplomatie',
  	'Modal_Title_Box' => 'Boîte de réception',
  	'Modal_Title_Delmsg' => 'Suppression',
  	'Modal_Title_Showmsg' => 'Voir un message',
  	'Modal_Title_Msg' => 'Ecrire un message',
  	'Modal_Title_Startmsg' => 'Accusé de réception',
  	'Modal_Title_Pact' => 'Proposer un traité',
  	'Modal_Title_Startpact' => 'Etat du traité',
  	'Modal_Title_Acceptpact' => 'Traité signé',
  	'Modal_Title_Move' => 'Déplacer des troupes',
  	'Modal_Title_Startmove' => 'Rapport de déplacement',
  	'Modal_Title_Buy' => 'Acheter des troupes',
  	'Modal_Title_Startbuy' => 'Rapport de la commande',
  	'Modal_Title_Build' => 'Construire',
  	'Modal_Title_Startbuild' => 'Rapport de construction',
  	'Modal_Title_Atk' => 'Attaque',
  	'Modal_Title_Startatk' => 'Resultat du combat',
];
?>