<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */

    // Left menu
    'Title_Game_List'       => 'Parties',
    'Title_Game_Create'     => 'Créer une partie',
    'Title_Compagny'        => 'Mes soci�t�s',
    'Title_Create'          => 'Cr�er une soci�t�',
    'Title_Dashboard'       => 'Tableau de bord',
    'Title_Employe'         => 'Employ�s',
    'Title_Finances'        => 'Finances',
    'Title_Game'            => 'Le jeu',
    'Title_GlobalDashboard' => 'Tableau de bord g�n�ral',
    'Title_Home'            => 'Accueil',
    'Title_Investment'      => 'Mes investissements',
    'Title_Login'           => 'Se connecter',
    'Title_Logout'          => 'Se déconnecter',
    'Title_Menu'            => 'Menu',
    'Title_Money'           => 'Argent',
    'Title_Product'         => 'Produits',
    'Title_Rank'            => 'Classement mondial',
    'Title_Research'        => 'Recherche',
    'Title_Sign'            => "S'inscrire",
    'Title_Stats'           => 'Statistiques mondiales',
    'Title_Trading'         => 'Bourse',
    'Title_Tutorial'        => 'Tutoriel',
    'Title_World'           => 'Dans le monde',
];
?>