<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	'Title_Welcome' => 'Bienvenue',
    'Title_Language' => 'Changer la langue',

	/* Text */
    'Home_Monark_Description' => 'Jeu de stratégie sur navigateur',
    'Home_Monark_Welcome' => 'Bienvenue sur Monark !',
	'Home_Registration_Description' => "Remplir le formulaire d'inscription pour jouer à Monark",
	'Home_Login_Description' => 'Créer un compte et se connecter pour lancer des parties',
	'Home_Tutorial_Description' => 'Apprendre à utiliser et jouer à Monark',
    'Success_Change_Lang' => 'Langue changée',
    'Registration_Rules' => 'Veuillez completer le formulaire pour créer votre partie :',

    /* Buttons */ 
    'Button_Registration' => "S'inscrire",
    'Button_Login' => "Se connecter",
    'Button_Tutorial' => "Tutoriel",
    'Button_Game_Map' => "Carte de la partie",
    'Button_Empire_Gestion' => "Gérer mon empire",
    'Button_Registration' => "S'inscrire",

    /* Actions */ 
    'Delete' => 'Supprimer',

    /* Lang */
    'en' => 'Anglais',
    'fr' => 'Français',
];