<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	
	/* Text */
	'Text_Not_User_Turn'		=> 'No actions available <br> Please wait your turn...',
	'Text_Land_No_Resource'		=> 'No resource',
	'Text_Land_No_Building'		=> 'No building',
	'Text_Land_Frontier'		=> 'Frontier with',
	'Text_Land_No_User_Frontier'=> 'You do not have a border country',
	'Text_No_More_Money'		=> 'You no longer have money',
	'Text_Resource_In_Land'		=> 'Resources in',
	'Text_In'					=> 'in',
	'Text_Units'				=> 'Units',
	'Text_Units_In'				=> 'Units in',
	'Text_Owner'				=> 'Owner',
	'Text_Owner_Player'			=> 'You',
	'Text_Resource'				=> 'Resource',
	'Text_Units_Pending'		=> 'units pending',
	'Text_Buy_To_Recruit'		=> 'Recruit unit',
	'Text_Build_In_Land'		=> 'Build in',
	'Text_Build_Able_Land'		=> 'Possible constructions in',
	'Text_Build_Other'			=> 'Build another',
	'Text_Move_Cant'			=> "Can't move any unit",
	'Text_Move_Units_NB'		=> 'Units to move',
	'Text_Move_Able_Land'		=> 'Possible destinations',
	'Text_Land_Nothing_To_Build'=> 'Nothing to build',
		
	/* Buttons */
	'Button_Land_Build' 		=> 'Build',
	'Button_Land_Buy' 			=> 'Recruit',
	'Button_Land_Atk' 			=> 'Attack',
	'Button_Land_Move' 			=> 'Move units',
	'Button_Move_Click' 		=> 'Move to',
	'Button_Return' 			=> 'Return',
		
	/* Error */
	'Error' 					=> 'Unknow error.',
	'Error_Turn' 				=> 'Error : this is not your turn.',
	'Error_Gold' 				=> 'Error : you have not enough gold.',
	'Error_Units' 				=> "Error : you must keep at least 1 unit in your territory.",
];
?>