<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	"To buy"		=> "To buy", 
	"To build"		=> "To build",
	"To move units"		=> "To move units",
	"To attack"		=> "To attack",

	'Text_Not_User_Turn'		=> 'No actions available <br> Please wait your turn...',
	/* Text */
	'Text_Land_No_Resource'		=> 'No resource',
	'Text_Land_No_Building'		=> 'No building',
	'Text_Land_Frontier'		=> 'Frontier with',
	'Text_Land_No_User_Frontier'=> 'You do not have a friendly border country',
	'Text_Land_No_Other_Frontier'=> 'You do not have an enemy border country',
	'Text_No_More_Money'		=> 'You no longer have money',
	'Text_Resource_In_Land'		=> 'Resources in',
	'Text_In'					=> 'in',
	'Text_Units'				=> 'Units',
	'Text_Units_In'				=> 'Units in',
	'Text_Owner'				=> 'Owner',
	'Text_Total'				=> 'Total',
	'Text_Income'				=> 'Income',
	'Text_Owner_Player'			=> 'You',
	'Text_Resource'				=> 'Resource',
	'Text_Units_Pending'		=> 'units pending',
	'Text_Buy_To_Recruit'		=> 'Recruit unit',
	'Text_Build_In_Land'		=> 'Build in',
	'Text_Build_Able_Land'		=> 'Possible constructions in',
	'Text_Build_Other'			=> 'Build another',
	'Text_Move_Cant'			=> "Can't move any unit",
	'Text_Move_Units_NB'		=> 'Units to move',
	'Text_Move_Able_Land'		=> 'Possible destinations',
	'Text_Atk_Able_Land'		=> 'Possible attackers',
	'Text_Atk_Units_NB'			=> 'Units to mobilize',
	'Text_Land_Nothing_To_Build'=> 'Nothing to build',
	'Text_Not_Owner'			=> "You don't own this land",
	'Text_Are_Owner'			=> "You own this land",
	'Text_Conquered_This_Turn' 	=> "conquered this turn.",
<<<<<<< HEAD

=======
	'Text_Income_By_Buildings'	=> 'buildings',
	'Text_Income_By_Lands'		=> 'lands',

>>>>>>> a35edda9d773178ebfe2b8a928a70f1e8bdb7418
	/* Buttons */
	'Button_Land_Build' 		=> 'Build',
	'Button_Land_Buy' 			=> 'Recruit',
	'Button_Land_Atk' 			=> 'Attack',
	'Button_Land_Atk_With' 		=> 'Attack with',
	'Button_Land_Move' 			=> 'Move units',
	'Button_Move_Click' 		=> 'Move to',
	'Button_Return' 			=> 'Return',

	/* Tooltips */
	"Attack this land."																				=> "Attack this land.",
	"Move units to another land."																=> "Move units to another land.",
	"Construct buildings on the land: fort, camp, mines."				=> "Construct buildings on the land: fort, camp, mines.",
	"Buy units for this land."																	=> "Buy units for this land.",

	/* Error */
	'Error' 					=> 'Unknow error.',
	'Error_Turn' 				=> 'Error : this is not your turn.',
	'Error_Gold' 				=> 'Error : you have not enough gold.',
	'Error_Units' 				=> "Error : you must keep at least 1 unit in your territory.",
	'Error_Conquest' 			=> "Error : this land was conquered this turn.",
];
?>
