<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	
	/* Text */
	'Text_Land_Not_User_Turn'	=> 'No actions available <br> Please wait your turn...',
	'Text_Land_No_Ressource'	=> 'No ressource',
	'Text_Land_No_Building'		=> 'No building',
	'Text_Land_Frontier'		=> 'Frontier with',
		
	/* Buttons */
	'Button_Land_Build' => 'Build',
	'Button_Land_Buy' => 'Buy',
	'Button_Land_Atk' => 'Attack',
	'Button_Land_Move' => 'Move units',
];
?>