<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */
	'Title_Lobby_{params}' => "{params} lobby",

    /* Text*/
    'Continent_Rules' => '* Information *: You have 1 in 5 chance to find yourself in Antarctica instead of your chosen continent !',
    'Text_Wait_Owner' => 'Game host waiting ...',
    'Text_Owner' => 'Host of the game',
    'Bot_Name_{id}' => 'Bot {id}',
    'Text_Add_Bot' => 'Bot added.',
    'Text_Bot_Del' => 'Bot deleted.',
    'Text_Player_Game_Ban' => 'Players removed from the game.',
    'Text_Error_Action' => 'Unable to complete this action.',

    /* Buttons */ 
    'Button_Sart_Game' => 'Start the game',
    'Button_Add_Bot' => 'Add a BOT',
    'Button_Ready' => 'I am ready',
    'Button_Cancel' => 'Cancel',
    'Button_Not_Ready' => 'Busy',
    'Button_Rdy' => 'I am ready',
    'Button_Add_Friend' => 'Invite a friend',
    'Button_Add_Random' => 'Invite a random player',

    /* Form */
    'Form_Continent' => 'Starting continent',
    'Form_Difficulty' => 'Difficulty',
    'Form_Color' => 'Color',
    'Form_Status' => 'Status',
    'Form_Player' => 'Player',

	/* Tab */
	'Tab_User_Name' => 'User name',
	'Tab_Color_Name' => 'Color',
	'Tab_Region_Player' => 'Departure area',
		
    /* Error */
    'Text_Forced_left' => 'You have been sacked of the lobby',
];
?>