<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	'Title_Create' => 'Create your game',
    'Title_Loby' => 'Game lobbies list',
    'Title_Join' => 'Join a game',
    'Title_Loading' => 'Loading...',
	'Title_Map' => 'Map',
	'Title_Game_Mail' => 'Message box',
	'Title_Game_Chat' => 'Game chat',
	'Title_Game_News' => 'Game news',
	'Title_Game_Stats' => 'Game stats',
	'Title_Game_Diplomacy' => 'Diplomacy',

	/* Tab */
	'Tab_Game_Name' => 'Game Name',
	'Tab_Owner_Name' => 'Owner Name',
	'Tab_Max_Player' => "Players",
	'Tab_Create_Time' => "Create time",
	'Tab_Rejoin' => "Join the game",

    /* Text*/
    'Creation_Rules' => 'Please complete the form to create your game :',
    'Join_Rules' => 'Please enter the password of the game :',
    'Chat_General' => 'General chat',
	'Text_Second_{nb}' => '{nb} sec ago',
	'Text_Min_{nb}' => '{nb} min ago',
	'Text_Hour_{nb}' => '{nb} h ago',
	'Text_Yesterday' => 'Yesterday',
	'Text_Week' => 'This week',
	'Text_Date' => 'm/d/Y',
	'Text_Load_Title' => 'Progression',
	'Txt_Map_Creation' => 'Creating map',
	'Txt_Region_Creation' => 'Creating regions',
	'Txt_Player_Creation' => 'Creating players',
	'Txt_Land_Assignation' => 'Assigning country',
	'Txt_Finalization' => 'Finalization',
	'Txt_Game_Owner_ID' => 'Game owner ID',
	'Txt_Game_Max_Player' => 'Game Max Player',
	'Txt_Game_Create_Time' => 'Game Create Time',
	'Txt_Game_Statut' => 'Game Statut',
	'Txt_Game_Map_ID' => 'Game Map ID',
	'Txt_Game_Mod_ID' => 'Game Mod ID',
	'Txt_Game_Turn_Time' => 'Game Turn Time',
	'Txt_Game_Difficulty_ID' => 'Game Difficulty ID',
	'Txt_Game_Won_User_ID' => 'Game Won User ID',
	'Txt_Game_Won_Time' => 'Game Won Time',
	'Txt_Game_Pwd' => 'Game Pwd',
	'Txt_Game_Key' => 'Game Key',

	/* Errors & success */
	'Error_Name_Already_Use' => 'Game name already used',
  'Error_Password_Incorrect' => 'A password is required : incorrect password.',
  'Error_User_Already_In_Game' => 'You are already playing in another game !',
  'Error_Game_Full' => 'The game is full.',
	'Error_Game_Cant_Join' => 'Impossible to reach the game.',
	'Error_Last_Game_Cant_Join' => 'Impossible to reach last game.',
  'Error_Game_Not_Exist' => "The game not exist anymore.",
  'Error_Start_Multiple_Color' => "The game can't start : Several players chose the same color.",
  'Error_Start_Not_Ready' => "The game can't start : Several players are not ready.",
  'Error_Start_Stop' => "The game can't start.",
	'Error_Max_Player_Nb' => "The maximum number of players is 10.",
	'Error_Not_Owner'	=> "You do not have authorization to perform this operation.",
  'Success_User_Left_Game' => 'You have left the game.',
  'Success_User_Enter_Game_{params}' => 'You have join the game : {params}.',
	'Success_Game_Created' => 'Game created.',
	'Success_Game_Join' => 'Game joined.',
	'Notice_Game_Quit' => 'Game exited.',
	'Notice_Games_Quit' => 'All open games are now exited.',
	'Notice_Last_Game_Entered' => 'Last game joined',



    /* Buttons */
    'Button_Send' => 'Send',
    'Button_Game_Create' => 'Create a game',
		'Button_Game_Enter' => 'Join the game',
		'Button_Map_Enter' => 'Join the map',
		'Button_Last_Game_Enter' => 'Return to last game',
    'Button_Game_Return' => 'Return to game',
    'Button_Game_Spec' => 'Spectate the game',
    'Button_Game_Ban' => 'You were ban of the game',
		'Button_Game_End' => 'End Game',
		'Button_Games_Quit' => 'Quit all open games',
	  'Button_Enter_In_Game' => 'Join the game',

    /* Form */
    'Form_Create_Name' => 'Name',
    'Form_Create_Time' => 'Creation',
    'Form_Create_Pwd' => 'Password',
    'Form_Create_Max_Player' => 'Number of players',
    'Form_Create_Mod_Id' => 'Game mode',
    'Form_Create_Difficulty_Id' => 'Difficulty',
    'Form_Create_Map_Id' => 'Map',
    'Form_Create_Owner' => 'Host of the game',
    'Form_Join_Pwd' => 'Password',
];
?>
