<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
     // Title
	'Title_Last_Buy'	=>  'Last purchases',
	'Title_Last_Chat'	=>  'Last messages',

    // header
	'Logout'       	=> 'Logout',
	'Profile'       => 'Profile',
	'Friends'       => 'Friends',
	'Settings'      => 'Settings',
	'Language'      => 'Language',

		
	// In game header
	// Buttons
    'Button_Chat' => "Show chat",
    'Button_Diplomacy' => "Diplomacy ",
    'Button_Turn_Own' => "End of turn",
	
	// box title
	'Box_Title_Ranking' => 'Ranking',
	'Box_Title_News' => 'News',
	'Box_Title_Pact' => 'Current treaties',
		
	 // Text
    'Text_Gold' => 'Gold',
    'Text_Income' => 'Income',
    'Text_Country' => 'Countries',
    'Text_Units' => 'Units',
    'Text_Turn_Own' => 'Remaining time',
	'Text_Turn_Lenght' => 'Turn length',
    'Text_Turn_Finished' => 'Turn finished',
    'Text_Turn_Other' => 'Please wait, turn of',
	'Text_Your_turn'	=>  "It's your turn !",
	'Text_Lost_Connection'=>  'Connection lost with the server',
	'Text_View_All'	=>  'View all',
	'Text_No_Unread_Chat' => 'No unread posts',
    
];
?>