<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */
	  'Title_Map' => 'Map of the game',

	  /* Text */
    'Text_Menu_Top_Gold' => 'Gold',
    'Text_Menu_Top_Income' => 'Income',
    'Text_Menu_Top_Country' => 'Countries',
    'Text_Menu_Top_Units' => 'Units',
    'Text_Turn_Own' => 'Remaining time',
    'Text_Turn_Finished' => 'Turn finished',
    'Text_Turn_Other_{name}' => '{name} turn.',

    /* Buttons */ 
    'Button_Chat_{nb}' => "Show chat ({nb})",
    'Button_Diplomacy' => "Diplomacy ",
    'Button_Turn_Own' => "End of turn",

    /* Box */ 
    // box title
    'Box_Title_Ranking' => 'Ranking',
    'Box_Title_News' => 'News',
    'Box_Title_Pact' => 'Current treaties',

    /* Modal */
    'Modal_Loading' => 'Loading',
    // Modal title
  	'Modal_Title_Land' => 'Information',
  	'Modal_Title_Gestion' => 'Manage',
  	'Modal_Title_Chat' => 'Chat',
  	'Modal_Title_NewTurn' => '',
  	'Modal_Title_Diplomacy' => 'Diplomacy',
  	'Modal_Title_Box' => 'Mailbox',
  	'Modal_Title_Delmsg' => 'Suppression',
  	'Modal_Title_Showmsg' => 'Show a message',
  	'Modal_Title_Msg' => 'Write a message',
  	'Modal_Title_Startmsg' => 'Acknowledgment',
  	'Modal_Title_Pact' => 'Submit a treaty',
  	'Modal_Title_Startpact' => 'Treaty status',
  	'Modal_Title_Acceptpact' => 'Treaty signed',
  	'Modal_Title_Move' => 'Move troops',
  	'Modal_Title_Startmove' => 'Move report',
  	'Modal_Title_Buy' => 'Buy troops',
  	'Modal_Title_Startbuy' => 'Buy report',
  	'Modal_Title_Build' => 'Build',
  	'Modal_Title_Startbuild' => 'Building report',
  	'Modal_Title_Atk' => 'Attack',
  	'Modal_Title_Startatk' => 'Combat result',
];
?>