<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    /* Title */

    // Left menu
    'Title_Game_List'       => 'Games',
    'Title_Game_Create'     => 'Create game',
    'Title_Game_Quit'       => 'Quit the game',
	'Title_Game_Map'        => 'Show the map',
	'Title_Game_Stats'      => 'Game stats',
	'Title_Game_Lobby'      => 'Game lobby',	
	'Title_Game_Mail' 		=> 'Message box',
	'Title_Game_Chat' 		=> 'Game chat',
	'Title_Game_News' 		=> 'Game news',
	'Title_Game_Diplomacy' 	=> 'Diplomacy',
		
    'Title_Create'          => 'Start corporation',
    'Title_Dashboard'       => 'Dashboard',
    'Title_Employe'         => 'Employees',
    'Title_Finances'        => 'Finances',
    'Title_Game'            => 'The game',
    'Title_GlobalDashboard' => 'Global Dashboard',
    'Title_Home'            => 'Home',
    'Title_Investment'      => 'My investments',
    'Title_Login'           => 'Login',
    'Title_Logout'          => 'Logout',
    'Title_Menu'            => 'Menu',
    'Title_Money'           => 'Money',
    'Title_Product'         => 'Products',
    'Title_Rank'            => 'Corp Ranking',
    'Title_Research'        => 'Research',
    'Title_Sign'            => 'Sign in',
    'Title_Stats'           => 'Global stats',
    'Title_Trading'         => 'Market',
    'Title_Tutorial'        => 'Tutorial',
    'Title_World'           => 'On the world',
    
];
?>