<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
	/* Title */
	'Title_Welcome' => 'Welcome',
    'Title_Language' => 'Switch language',
    
	/* Text */
    'Home_Monark_Description' => 'Browser strategy game',
    'Home_Monark_Welcome' => 'Welcome to Monark !',
    'Success_Change_Lang' => 'Language changed',
	'Home_Registration_Description' => "Complete the registration form to play Monark",
	'Home_Login_Description' => 'Create an account and log in to start games',
	'Home_Tutorial_Description' => 'Learning how to play Monark',

    /* Buttons */ 
    'Button_Registration' => 'Register',
    'Button_Login' => 'Log in',
    'Button_Tutorial' => 'Tutorial',
    'Button_Game_Map' => 'Game map',
    'Button_Empire_Gestion' => 'Manage my empire',
    'Button_Registration' => 'Register',

    /* Actions */ 
    'Delete' => 'Delete', 

	/* Lang */
	'en' => 'English',
	'fr' => 'French',
];